### ISSUE TITLE
Addon installation broken under ember-cli v0.2.2

### ISSUE THREAD

**Issue by jacojoubert** [taras/ember-cli-velocity#2]
Installing the addon under the latest version of ember-cli breaks because `pickFiles` and `mergeTrees` has been deprecated.

`[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-cli-velocity]
[Deprecated] this.mergeTrees is deprecated, please use broccoli-merge-trees directly instead  [addon: ember-cli-velocity]
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-cli-velocity]
[Deprecated] this.mergeTrees is deprecated, please use broccoli-merge-trees directly instead  [addon: ember-cli-velocity]`

**Comment by taras** [comment]
Ok, I'll update it, unless you want to make a PR first ;)

**Comment by taras** [comment]
Just pushed 0.3.1, should work. Please give it a try.

**Comment by runspired** [comment]
This was resolved by the fixes above.
